In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("job_salary_prediction_dataset.csv")

In [5]:
df.head()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069

In [6]:
df.tail()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
249995,Software Engineer,17,PhD,2,Telecom,Enterprise,India,No,1,127791
249996,Frontend Developer,20,PhD,7,Telecom,Startup,Remote,No,2,154593
249997,Business Analyst,1,Bachelor,12,Retail,Enterprise,India,Yes,0,75988
249998,Data Scientist,0,High School,2,Consulting,Small,Sweden,Hybrid,5,90467
249999,Data Analyst,16,Diploma,2,Technology,Medium,UK,No,5,133084

In [8]:
df.shape

(250000, 10)

In [10]:
 df.columns

Index(['job_title', 'experience_years', 'education_level', 'skills_count',
       'industry', 'company_size', 'location', 'remote_work', 'certifications',
       'salary'],
      dtype='object')

In [11]:
df.dtypes

job_title           object
experience_years     int64
education_level     object
skills_count         int64
industry            object
company_size        object
location            object
remote_work         object
certifications       int64
salary               int64
dtype: object

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   job_title         250000 non-null  object
 1   experience_years  250000 non-null  int64
 2   education_level   250000 non-null  object
 3   skills_count      250000 non-null  int64
 4   industry          250000 non-null  object
 5   company_size      250000 non-null  object
 6   location          250000 non-null  object
 7   remote_work       250000 non-null  object
 8   certifications    250000 non-null  int64
 9   salary            250000 non-null  int64
dtypes: int64(4), object(6)
memory usage: 19.1+ MB

In [13]:
df.isnull().sum()

job_title           0
experience_years    0
education_level     0
skills_count        0
industry            0
company_size        0
location            0
remote_work         0
certifications      0
salary              0
dtype: int64

In [14]:
missing_percentage = df.isnull().mean() * 100

print(missing_percentage)

job_title           0.0
experience_years    0.0
education_level     0.0
skills_count        0.0
industry            0.0
company_size        0.0
location            0.0
remote_work         0.0
certifications      0.0
salary              0.0
dtype: float64

There is no null values but we will do to fix because its for learning and helful for that cases if we face any missing values problems this data set is from kaggle.

In [15]:
df = df.dropna()

In [16]:
df["experience_years"] = df["experience_years"].fillna(df["experience_years"].median())

Replace with median

In [17]:
df["experience_years"] = df["experience_years"].fillna(df["experience_years"].mean())

replace with mean

In [18]:
df["education_level"] = df["education_level"].fillna(df["education_level"].mode()[0])

Replace with most frequent value

In [20]:
df.duplicated().sum()

np.int64(0)

In [21]:
df = df.drop_duplicates()

Remove duplicates if any

In [22]:
df.dtypes

job_title           object
experience_years     int64
education_level     object
skills_count         int64
industry            object
company_size        object
location            object
remote_work         object
certifications       int64
salary               int64
dtype: object

check data types if any data type is incorrect so we will fix it first

In [23]:
df["salary"] = df["salary"].astype(float)

In [24]:
df["education_level"].unique()

array(['Bachelor', 'PhD', 'High School', 'Diploma', 'Master'],
      dtype=object)

In [25]:
df["education_level"] = df["education_level"].replace({
    "bachelor":"Bachelor",
    "Bachelors":"Bachelor",
    "Bachelor Degree":"Bachelor",
    "masters":"Master",
    "Master Degree":"Master",
    "phd":"PhD"
})

if you see some mistakes so you can check it first

In [26]:
df["job_title"] = df["job_title"].replace({
    "Software Eng.":"Software Engineer",
    "Software Developer":"Software Engineer",
    "SWE":"Software Engineer"
})

In [27]:
df["job_title"] = df["job_title"].str.strip()

In [28]:
text_columns = df.select_dtypes(include="object").columns

for col in text_columns:
    df[col] = df[col].str.strip()

remove All extra spaces in text coloumns

In [29]:
df["education_level"] = df["education_level"].str.title()

In [30]:
df["salary"].describe()

count    250000.000000
mean     145718.080524
std       37407.952729
min       31867.000000
25%      119358.000000
50%      143453.000000
75%      169492.000000
max      333046.000000
Name: salary, dtype: float64

In [31]:
Q1 = df["salary"].quantile(0.25)

Q3 = df["salary"].quantile(0.75)

IQR = Q3 - Q1

outliers

In [32]:
lower = Q1 - 1.5*IQR

In [33]:
upper = Q3 + 1.5*IQR

In [34]:
outliers = df[(df["salary"] < lower) | (df["salary"] > upper)]
len(outliers)

2336

In [35]:
(df["salary"] < 0).sum()

np.int64(0)

In [36]:
(df["experience_years"] < 0).sum()

np.int64(0)

In [37]:
df["experience_years"].describe()

count    250000.000000
mean         10.005408
std           6.060602
min           0.000000
25%           5.000000
50%          10.000000
75%          15.000000
max          20.000000
Name: experience_years, dtype: float64

In [38]:
exchange_rates = {
    "USD": 1,
    "SAR": 3.75,
    "INR": 83.5,
    "EUR": 0.92,
    "PKR": 275
}

In [42]:
X = df.drop("salary", axis=1)
y = df["salary"]

In [43]:
exchange_rate = 0.0135

df["salary_sar"] = df["salary"] * exchange_rate

In [44]:
exchange_rate = 3.76

df["salary_sar"] = (df["salary"] * exchange_rate).round(2)

In [45]:
df[["salary", "salary_sar"]].head()

     salary  salary_sar
0  109413.0   411392.88
1   93764.0   352552.64
2  148123.0   556942.48
3  189123.0   711102.48
4  165069.0   620659.44

In [46]:
df["job_title"].value_counts()

job_title
Backend Developer            21125
Cybersecurity Analyst        20959
Product Manager              20950
AI Engineer                  20945
Data Scientist               20890
DevOps Engineer              20889
Software Engineer            20876
Data Analyst                 20722
Cloud Engineer               20686
Machine Learning Engineer    20677
Business Analyst             20648
Frontend Developer           20633
Name: count, dtype: int64

In [47]:
df["education_level"].value_counts()

education_level
Master         50352
High School    50065
Bachelor       49950
Phd            49857
Diploma        49776
Name: count, dtype: int64

In [48]:
df.to_csv("clean_salary_dataset.csv", index=False)